# Generated by Django 4.2.1 on 2023-06-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_oferta'),
        ('core', '0004_venta_estado_alter_venta_fecha'),
    ]

    operations = [
    ]
