# Generated by Django 4.2.1 on 2023-06-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20230624_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Detalle',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
