# Generated by Django 4.2.1 on 2023-07-04 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_venta_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 7, 4, 21, 47, 4, 592480, tzinfo=datetime.timezone.utc)),
        ),
    ]
